apiVersion: v1
kind: ServiceAccount
metadata:
  name: clipper-api
  namespace: clipper
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clipper-worker
  namespace: clipper
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clipper-frontend
  namespace: clipper
automountServiceAccountToken: false

