apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clipper-api
  namespace: clipper
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clipper-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: clipper-worker
  namespace: clipper
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clipper-worker

